# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22757476861f581b4047e56a78300f5d8e1788e340bbe2b2687bd6008efed776847f4c88f83680c499181fc09271560a652060e1cbcf20e897c097e38be0413a

test:
  secret_key_base: cf89a887e6c80971d9414804957ea6a664adf79743977bf0424118d264907675e22711b6ea3767da3d677139dba0b3cee41f2ba94bc4f38675f73b4ccf1c7688

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
